---
baseURL: 'https://gonetraveling.me'
languageCode: "en-GB"
title: Gone Traveling
theme:
  - hugo-cloak-email
googleAnalytics: UA-51745895
author:
  name: Kyle Welsby
  email: kyle@mekyle.com
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: -1
---